# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('region', models.PositiveSmallIntegerField(blank=True, choices=[(44, 'Alsace-Champagne-Ardenne-Lorraine'), (75, 'Aquitaine-Limousin-Poitou-Charentes'), (84, 'Auvergne-Rh\xf4ne-Alpes'), (27, 'Bourgogne-Franche-Comt\xe9'), (53, 'Bretagne'), (24, 'Centre-Val de Loire'), (94, 'Corse'), (11, '\xcele-de-France'), (76, 'Languedoc-Roussillon-Midi-Pyr\xe9n\xe9es'), (32, 'Nord-Pas-de-Calais-Picardie'), (28, 'Normandie'), (52, 'Pays de la Loire'), (93, "Provence-Alpes-C\xf4te d'Azur")], null=True)),
                ('tour', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1er Tour'), (2, '2eme Tour')], null=True)),
                ('nom_de_liste', models.TextField(blank=True, null=True)),
                ('tete_de_liste', models.CharField(blank=True, max_length=255, null=True)),
                ('appreciatifs', models.IntegerField(blank=True, null=True)),
                ('modalite_deontique', models.BooleanField()),
                ('deictiques_personnels', models.TextField(blank=True, null=True)),
                ('deictiques_spatiaux', models.TextField(blank=True, null=True)),
                ('deictiques_temporels', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
