# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='modalite_deontique',
            field=models.BooleanField(default=False),
        ),
    ]
