# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151220_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
