# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20151220_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tract',
            name='phrase_deontique',
            field=models.TextField(default=False),
        ),
    ]
