# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tract_phrase_deontique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='phrase_deontique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
